apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: api-service
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console-service
      port: {{ .Values.app.consolePort }}
      targetPort: {{ .Values.app.consolePort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9000
          - containerPort: {{ .Values.app.consolePort }}
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-investing
                  key: minio-password
            - name: MINIO_CONSOLE_ADDRESS
              value: ":{{ .Values.app.consolePort }}"
          volumeMounts:
            - name: data
              mountPath: {{ $.Values.storage.mountPath}}
          command:
          - sh
          - -c
          - minio server {{ $.Values.storage.mountPath}}
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}