app:
  consolePort: 9001 # MINIO API PORT IS 9000, CONSOLE PORT IS RANDOM UNLESS WE SELECT, WE GO FOR 9001

storage:
  size: 10Gi # IF SUPPORTED BY STORAGE CLASS, PVCs CAN BE MANUALLY RESIZED AFTER INITIAL RELEASE!
  mountPath: "/pvc"